### ISSUE TITLE
Missing parentheses causing EISDIR read error

### ISSUE THREAD

**Issue by agillaspie** [marcbachmann/node-html-pdf#116]
When the filename is being constructed in the **page.onLoadFinished** method, the if statement on [line 65](https://github.com/marcbachmann/node-html-pdf/blob/master/lib/scripts/pdf_a4_portrait.js#L65) isn't returning the correct value. The way it's constructed, if options.directory exists, that is used as the entire filename.. which causes a file read error.

`(options.directory || '/tmp' + '/html-pdf-' + system.pid + '.' + fileOptions.type)`
...should be...
`(options.directory || '/tmp') + '/html-pdf-' + system.pid + '.' + fileOptions.type`

**Comment by marcbachmann** [comment]
Shit, that happened when I migrated the file to javascript: https://github.com/marcbachmann/node-html-pdf/blob/6bb48cfa6879b89764105f60b9c4c174576d1784/src/scripts/pdf_a4_portrait.coffee#L157

**Comment by marcbachmann** [comment]
Fixed in #117 and released as v2.0.1
