### ISSUE TITLE
Tabe with header on each page

### ISSUE THREAD

**Issue by reddyrenuka** [marcbachmann/node-html-pdf#121]
I am trying to render a table in pdf which spawns across multiple pages. I want the header to appear on every page.
I tied multiple things including having a thead, tbody etc but nothing worked.
When viewed in html and printed to pdf from the browser, the page renders correctly with table headers on each page. Please help.

**Comment by marcbachmann** [comment]
https://github.com/marcbachmann/node-html-pdf/issues/46
