### ISSUE TITLE
Error: write EPIPE

### ISSUE THREAD

**Issue by danielsun174** [marcbachmann/node-html-pdf#124]
I'm trying to use the module with ubuntu v14.04 ( via docker ).
When trying 'html-pdf index.html index.pdf' is give the following error:

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write EPIPE
>     at exports._errnoException (util.js:870:11)
>     at WriteWrap.afterWrite (net.js:769:14)

My Ubuntu-Version:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

When running the same command on the same machine with linux-mint, it works as aspected.

**Comment by marcbachmann** [comment]
Please try `sudo apt-get install libfontconfig`
https://github.com/marcbachmann/node-html-pdf/issues/35

**Comment by danielsun174** [comment]
Thank you very much. It works :+1:

**Comment by marcbachmann** [comment]
you're welcome

**Comment by BhavanPatel** [comment]
ERROR: Caught exception: Error: read ECONNRESET
	server-0 Error: read ECONNRESET
	server-0     at exports._errnoException (util.js:746:11)
	server-0     at Pipe.onread (net.js:561:26)
	
solution:
sudo apt-get install libfontconfig.

**Comment by wegorich** [comment]
sudo apt-get install libfontconfig not helps anymore ununtu 16.04

**Comment by mvkanha** [comment]
What about window ?
