### ISSUE TITLE
PhantomJS not found on PATH

### ISSUE THREAD

**Issue by vasco3** [marcbachmann/node-html-pdf#127]
when installing using npm I see the following error
```
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-linux-x86_64.tar.bz2
```

There is an extra slash after the v2.1.1

**Comment by marcbachmann** [comment]
`PhantomJS not found on PATH`
That's not really a problem. Because you don't have phantomjs locally, it tries to download the phantomjs.

Do you get another error after the download log? Maybe it's just a formatting bug.
That issue would belong to https://github.com/medium/phantomjs/issues

**Comment by vasco3** [comment]
oh ok thanks. Yeah it's not a blocker. The module works perfectly. Thanks so much
