### ISSUE TITLE
Page Counter to be displayed

### ISSUE THREAD

**Issue by hariskhan10** [marcbachmann/node-html-pdf#131]
Hello,  is there any way to display a page counter like Page 1/2 or Page 2/2 on exporing the file to pdf?

**Comment by marcbachmann** [comment]
That's supported in the header and footer by using `{{page}}` and `{{pages}}`

```html
<body>
    <div id="pageHeader">Header</div>
    <div id="pageContent">Some content.</div>
    <div id="pageFooter">Page {{page}} of {{pages}}</div>
  </body>
```

**Comment by hariskhan10** [comment]
dear @marcbachmann 
i tried that function in <div id="pageFooter">Page {{page}} of {{pages}}</div> ,
can we use that directive to anywhere in the page

**Comment by marcbachmann** [comment]
> can we use that directive to anywhere in the page

No, sorry, that doesn't work.
The evaluation of the header and footer happens separately from the content.
Maybe you can try something with javascript. But that might be error prone.

**Comment by marcbachmann** [comment]
#168 now also exposes this as config option

**Comment by marcbachmann** [comment]
But still not in the content, only in header & footers. 
I'll close this for now.
