### ISSUE TITLE
Remove padding below pageHeader/pageFooter

### ISSUE THREAD

**Issue by drbarto** [marcbachmann/node-html-pdf#148]
When using a page header/footer, a huge padding is automatically inserted below it in the PDF. The padding between header and content is a bit larger than between footer and the end of the page; like this:

    -----------
    Header
      (padding)
      (padding)
      (padding)
    Content
    Content
    Content
    Footer
      (padding)
      (padding)
    -----------

My options don't specify a border or padding:

    var options = {
      format: 'A4',
      orientation: 'portrait',
      type: 'pdf'
    };

Here's how I generate the PDF:

    htmlPdf.create(html, options).toFile('./report.pdf', ...);
    
Is this padding added by html-pdf on purpose? How can I get rid of it?

**Comment by marcbachmann** [comment]
In case there's no height defined, the script is setting that: https://github.com/marcbachmann/node-html-pdf/blob/master/lib/scripts/pdf_a4_portrait.js#L191-L192

I think I've done this because phantomjs itself has a default height which is not documented.
Can you try to set `null` or `0` and see what happens?

**Comment by drbarto** [comment]
Hey, thanks a lot -- your hint fixed my problem!

I had to explicitly set the header/footer height to a value > 0 to make it work (0 or null were no good). Also, I previously had my header/footer contents defined in HTML, which did not work in conjunction with setting the height in JS; so I had to move the contents to JS as well:

    var options = {
      // ...
      header: {
        contents: 'my title',
        height: '10mm'
      },
      footer: {
        contents: '{{page}}/{{pages}}',
        height: '10mm'
      }
    };
