### ISSUE TITLE
Error with setting header and footer

### ISSUE THREAD

**Issue by ArunMichaelDsouza** [marcbachmann/node-html-pdf#156]
I am getting ``undefined`` appended to the header and footer that I am trying to add to the PDF document. 

![screen shot 2016-07-08 at 7 04 43 pm](https://cloud.githubusercontent.com/assets/4924614/16689141/1cb55ee0-453f-11e6-9999-c75c82afe960.png)

**Comment by iptaylortechnical** [comment]
We've got the same issue here.

After some testing, we're fairly certain this occurs when you have svgs that have <style> tags in them. Can you confirm this?

**Comment by ArunMichaelDsouza** [comment]
That is correct! The issue occurs when I use SVGs with the header and footer option added. As you can see in the snapshot above, it happens when I try to use the SVG graph on the page.

**Comment by iptaylortechnical** [comment]
@marcbachmann can you confirm this?

![48de25cf1343645d68b316fa65dab9b95cc9012a50](https://cloud.githubusercontent.com/assets/12981251/17027269/1b0fa7f2-4f18-11e6-944f-01695b229f5b.png)

without-test.js:

```
let pdf = require('html-pdf');
var htmlString = '' +
	'<p>hello</p>' +
	'<br>' +
	'<svg viewBox="0 0 1 1">' +
	'<path d="m0,0v1h1V0"/>' +
	'</svg>';
pdf.create(htmlString, {
	header: {
		 height: "2cm",
		 content: "<p>hello</p>"
	},
	footer: {
		 height: "2cm",
		 content: "<p>hello</p>"
	}
}).toFile('withoutStyleTags.pdf', function(){});
```

with-test.js

```
let pdf = require('html-pdf');
var htmlString = '' +
	'<p>hello</p>' +
	'<br>' +
	'<svg viewBox="0 0 1 1">' +
	'<style></style>' + //added line
	'<path d="m0,0v1h1V0"/>' +
	'</svg>';
pdf.create(htmlString, {
	header: {
		 height: "2cm",
		 content: "<p>hello</p>"
	},
	footer: {
		 height: "2cm",
		 content: "<p>hello</p>"
	}
}).toFile('withStyleTags.pdf', function(){});
```
