### ISSUE TITLE
individual border for top, right, bottom and left

### ISSUE THREAD

**Issue by Lichtjaeger** [marcbachmann/node-html-pdf#16]
Is there a chance to pass an object like this into the border option:

    {
    top: '1cm',
    right: '2cm',
    bottom: '1cm',
    left: '2cm'
    }

It would make it sometimes much easier.

**Comment by marcbachmann** [comment]
That's working already. But I guess this border will be white.
```
var options = {
  top: '1cm',
  right: '2cm',
  bottom: '1cm',
  left: '2cm'
};
pdf.create(html, options).toFile(callback);
```

**Comment by Lichtjaeger** [comment]
Thanks. until now I've only seen your example with:
    border: '0'

**Comment by marcbachmann** [comment]
Sorry, forgot to document that. I updated the readme with that configuration option.

**Comment by agiratech-reddysai** [comment]
how to change border color
