### ISSUE TITLE
Failed to convert for big file.

### ISSUE THREAD

**Issue by jianri** [marcbachmann/node-html-pdf#17]
I tried to convert html to pdf with this module, and html file size is over 3MB. 
But it failed to convert. Converted pdf file size is variable for each case, and it's about 70~90MB.
What's a reason for this? How can I solve this issue?

**Comment by marcbachmann** [comment]
Sadly on some environments, phantomjs fails to render the text correctly. Phantom renders it as paths.
I experience the same on os x but it’s working on ubuntu & debian.

**Comment by jianri** [comment]
Hi, Thanks for quick reply.

So do you mean this issue is from OS X? If I run this on Ubuntu, this issue will not occur?

**Comment by marcbachmann** [comment]
Yes, most users experienced the issue only on OS X.
I once had issues on Ubuntu 12.04. So I’m not dead sure whether it works for you.

**Comment by jianri** [comment]
ok, thanks.

**Comment by marcbachmann** [comment]
I guess I'll have to add FAQs to the readme. :smile:
