### ISSUE TITLE
Still, flex isn't supported

### ISSUE THREAD

**Issue by rayax86** [marcbachmann/node-html-pdf#172]
Just noticed that the `flex` clause declared in CSS is still not supported; rewritten to `-webkit-flex` and problem solved. This issue is claimed to be solved [here](https://github.com/marcbachmann/node-html-pdf/issues/24)

Using v2.1.0, rMBP 15' 2012.

**Comment by giacomoratta** [comment]
any solutions?

**Comment by maxmarkus** [comment]
This is clearly a [PhantomJS issue](https://github.com/ariya/phantomjs/issues/14365#issuecomment-254689736), please look there for workarounds, I directly linked to one which can be used if you render your own pages.

**Comment by rayax86** [comment]
Nice. I guess we can close this issue now.

**Comment by luisvquintas** [comment]
try display: -webkit-flex;

**Comment by amaneer94** [comment]
{ `flex: 1;` } is still not working for me. I am stuck. I even have tried [Autoprefixer CSS online
](https://autoprefixer.github.io/) `{
-webkit-box-flex: 1;
    -ms-flex: 1;
        flex: 1;
}
`

**Comment by jjuannn** [comment]
still not working 👎🏻

**Comment by danielnydrle** [comment]
[Autoprefixer](https://autoprefixer.github.io/) helped me with that, you have to change the names of the attributes sometimes, it works, the biggest problem I had was that I had to use `display: -webkit-box;` instead of `display: flex;` in some occasions.

**Comment by vladkrasn** [comment]
> [Autoprefixer](https://autoprefixer.github.io/) helped me with that, you have to change the names of the attributes sometimes, it works, the biggest problem I had was that I had to use `display: -webkit-box;` instead of `display: flex;` in some occasions.

Autoprefixer fixed my issue with flexing as well!
