### ISSUE TITLE
Cannot load local images as css background

### ISSUE THREAD

**Issue by angrykoala** [marcbachmann/node-html-pdf#177]
After trying the options on #119 (and with/without url("")) I'm not able to use a local image as `background-image` in the css.

The html is working before converting to pdf, and it works with online images, changing the base in configuration or using absolute paths (`file///...`) doesn't seem to fix the problem

**Comment by angrykoala** [comment]
I was able to make it work by using the full path (`file:/// ...`) inside the url:

```css
background-image: url("file:///home/arthurdent/images/myimage.jpg");
```

**Comment by golubvladimir** [comment]
I have the same problem, I have tried inline styles and css in style tag.
