### ISSUE TITLE
Doesn't work as service

### ISSUE THREAD

**Issue by Lichtjaeger** [marcbachmann/node-html-pdf#179]
Sorry to bother you with that, but i can not handle it.

Starting the app with `node ...` works. But if I run the same app with pm2 i get:

```
Error: write EOF
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite (net.js:795:14)
```

I tried a reduced test app (your example code) and got the same behavior but an other message:

```
Error: SetProcessDpiAwareness failed: "COM error 0x80070005  (Unknown error 0x0ffffffff80070005)"

    at ChildProcess.<anonymous> (C:\node\test\node_modules\html-pdf\lib\pdf.js:121:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

Same with `.toBuffer` and `.toFile`

Server: Windows Server 2012 R2
Node: 6.5.0
pm2: 2.0.7 (as a service: pm2-windows-service@0.2.0)
html-pdf: 2.1.0

I hope there is a solution.

**Comment by marcbachmann** [comment]
Indeed very strange that this only happens using `pm2`.
Do you execute that process with a different user that has access to executables (different $PATH)?

I only found this issue in phantomjs: https://github.com/ariya/phantomjs/issues/14095

**Comment by Lichtjaeger** [comment]
Pm2 is started as a service. So the user is SYSTEM.

But you are right. I copied the project to my local PC and run pm2 manually. It worked.

It must be something with the service.

To try different service solutions I need to restart the server multiple times and I can't do this till weekend.

**Comment by Lichtjaeger** [comment]
Yes, if I run it under a service it doesn’t work. It looks like it loses some privileges.

My workaround:
Using [registry startup](https://www.npmjs.com/package/pm2-windows-startup) and [autologon](http://www.geekality.net/2014/08/26/automatic-login-for-windows-server-2012-r2/)

Not a good solution but works for the moment.

PS: Changing the Issue title.

**Comment by marcbachmann** [comment]
I guess that's an issue that belongs to phantomjs itself.  I'm sorry
