### ISSUE TITLE
Html page cut off 

### ISSUE THREAD

**Issue by hao-feng** [marcbachmann/node-html-pdf#19]
When I convert my html page to pdf, the page doesn't fit the pdf width, and the right side get cut off.
The simple html is just using width="100%"

**Comment by marcbachmann** [comment]
Do you have the sample html? Are you using a viewport meta tag?

**Comment by hao-feng** [comment]
Finally, I found it was actually the problem of that webpage. Sorry for interrupt.
But I can't get the viewportsize option to work. Is there any example I can follow?
