### ISSUE TITLE
childprocess.spawn is not a function

### ISSUE THREAD

**Issue by VictorSage** [marcbachmann/node-html-pdf#194]
I received following error on this line.
Uncaught TypeError: childprocess.spawn is not a function

``` javascript
 child = childprocess.spawn(this.options.phantomPath, [].concat(this.options.phantomArgs, 
```

Does this package work on pure client side? What is the running environment for this package?

**Comment by marcbachmann** [comment]
No, sorry. It only works on node.

**Comment by VictorSage** [comment]
okay.
