### ISSUE TITLE
Make the conversion wait for a specific amount of time

### ISSUE THREAD

**Issue by dgmneto** [marcbachmann/node-html-pdf#197]
There should be an option that would wait for a determined amount of time before the conversion would happen. This is useful for pages that can take some time to load completely and might have some AJAX requests to be done.

**Comment by anthonycole** [comment]
+1 on this. Does anyone know of a workaround? Some of the other libraries have this and it's great but have massive drawbacks.

**Comment by hzhu** [comment]
Currently trying to convert D3/svg after some API calls for data. This would be an awesome feature if it didn't already exist.

**Comment by edkotkas** [comment]
Would be nice if there was a way to trigger the conversion after the a javascript trigger. Is it possible by any chance?

**Comment by taylorwan** [comment]
bump on this. this would be very helpful!

**Comment by edkotkas** [comment]
@taylorwan look at this PR https://github.com/marcbachmann/node-html-pdf/pull/264

**Comment by marcbachmann** [comment]
Released in v2.2.0
