### ISSUE TITLE
Simple CSS in <style> tag not working

### ISSUE THREAD

**Issue by molerat619** [marcbachmann/node-html-pdf#204]
Hi, I have following html and css code:

```html
<style type="text/css">
   /*<![CDATA[*/
      #pdf {
         background: green;
         font-family: "Open Sans", sans-serif;
      }
     /*]]>*/
</style>
<div id="pdf">
      <h3>My title</h3>
</div>
```

And I get zero styling in my pdf. What am I doing wrong?

**Comment by molerat619** [comment]
Ok, I just had to use the whole <html> wrapper.

**Comment by williamknn** [comment]
@molerat619 I did not understand what you meant by "use the whole html wrapper".
My html looks like this:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RoutEasy - Relatório Personalizado</title>
    <style type="text/css">
         body { background: red; }
    </style>
</head>
<body>
    <div>Lorem ipsum dolor sit amet consectetur our</div>
</body>
</html>
```

**Comment by molerat619** [comment]
What I meant by that was that I used only the code that was inside the body-tag. Not the whole <html><head>.... stuff.

**Comment by ankitjena** [comment]
@williamknn Did you manage to find any way around it, I am facing the same issue
