### ISSUE TITLE
Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'

### ISSUE THREAD

**Issue by liatreis** [marcbachmann/node-html-pdf#208]
Is this error message to be expected with normal usage? I do not have PhantomJS installed locally, but assumed that this module would download it as a dependency. I'm only having this issue on one particular device at this stage, but am worried it might also fail when deployed to Heroku.

It says in the readme `PhantomJS binary which should get downloaded automatically`, any idea what might be happening?

**Comment by liatreis** [comment]
Upon further investigation, it looks like the issue is with yarn not installing optional dependencies.

**Comment by marcbachmann** [comment]
Are there still optional deps problems with yarn? which version do you use?

**Comment by liatreis** [comment]
This was with 0.17.0, I think it *may* have worked with 0.16.x on my other device...

**Comment by liatreis** [comment]
Have resolved this by locking the version to 2.1.4 which is what `html-pdf` was using. Seems the binary in 2.1.13 is broken, as the same error pops up when you try to run it via command line.

**Comment by marcbachmann** [comment]
I don't have any problems with 2.1.13. What OS are you on?

**Comment by adambuczynski** [comment]
OS X Sierra

**Comment by vivekiyer114** [comment]
I am still facing this issue
Any help ??

OS : MacOS high sierra

**Comment by AlbertHambardzumyan** [comment]
Works fine on macOS Mojave.

Failed to deploy on AWS ELB instance Facing the same error described above.

**Comment by nomankt** [comment]
some find a solution?

**Comment by adamreisnz** [comment]
Yeah man, stop using PhantomJS.
To generate PDF, i recommend to just use headless Chrome instead.
