### ISSUE TITLE
using node-html-pdf with FileSaver.js

### ISSUE THREAD

**Issue by spyshow** [marcbachmann/node-html-pdf#213]
hi everyone:

i'm using this module in my Electron app to convert some database data into html string and then convert it to a pdf file. but i want to show the user a 'save as' dialog instead of saving it to a specific folder .. 
i couldn't find a way to do that .... can any body help me with this?

**Comment by marcbachmann** [comment]
I've used something like that in the past. Sorry for the coffee-script.
And that code was for an older electron-shell app. So you'll need to use some newer apis.

```coffee
      path = require('path')
      pdf = require('html-pdf')
      dialog = require('remote').require('dialog')
      dialog.showSaveDialog
        filters: [{ name: 'PDFs', extensions: ['pdf']}]
        title: 'Save the Order as PDF'
        defaultPath: path.join(config.desktopDir, @title()+'.pdf')
      , (filename) =>
        return unless filename
        filename = @title()+'.pdf' unless /\.pdf$/.test(filename)
        localStorage.setItem('fileDialogWorkingDir', path.dirname(filename))

        template = require('./libs/template').render 'order.html', this, (err, html) =>
          return callback(err) if err

          pdf.create( html, {timeout: 30000, filename: filename}).save (err) ->
            return callback(err) if err
            callback(null, filename)
```

**Comment by spyshow** [comment]
it give an error that the `pdf.create(...).save is not a function` .... what should i use instead of it ?

**Comment by marcbachmann** [comment]
Oh, that api might have changed. I guess you can use `pdf.create(html).toFile('path/to/file')`

**Comment by spyshow** [comment]
thank you very much
here what worked for me : 
    
    dialog.showSaveDialog({
          filters: [{ name: 'PDFs', extensions: ['pdf']}],
                        title: 'Save the Report as PDF',
                        defaultPath: path.join(app.getPath('desktop'), 'title1'+'.pdf')}
           , function(filename) {
                        
           pdf.create(docx).toFile(filename,function(err, res){
                  console.log(res.filename);
           });
                    
       });
