### ISSUE TITLE
Embedded pdf in html

### ISSUE THREAD

**Issue by GCorbel** [marcbachmann/node-html-pdf#216]
Hi,

I know this is a pretty specific issue but I think it can be interesting. I have an html with embedded pdf inside like : 

    <object data="test.pdf" type="application/pdf" width="300" height="200">
	<embed src="test.pdf" />
    </object>

I tried to generate a pdf with this html but I simply have nothing. It can be nice to include the source into the generated pdf. What you think ?

**Comment by maxmarkus** [comment]
Can only guess what you try to achieve here, but it seems a bit weird, you try to embed an pdf into an pdf then, that you can scroll (since you specify width + height?! If yes, then his is not possible in pdf.

**Comment by GCorbel** [comment]
I think this is simply not possible. Thanks.
