### ISSUE TITLE
PhantomJS Command Line Options

### ISSUE THREAD

**Issue by cnaccio** [marcbachmann/node-html-pdf#22]
How do we go about passing command line options to phantomjs? For instance I need to pass the --ignore-ssl-errors=yes option. See this page to see what I'm talking about: http://phantomjs.org/api/command-line.html

**Comment by marcbachmann** [comment]
Sorry, that's not yet possible. I'd accept pull requests.

**Comment by cnaccio** [comment]
Can I modify the source to accomplish this? If so where could I hard code in my additional parameters to the call to phantomjs?

**Comment by marcbachmann** [comment]
https://github.com/marcbachmann/node-html-pdf/blob/master/src/pdf.coffee#L72

You can edit this file & run `npm test` once. By running `npm test` it creates all the js files out of the coffee-script source.

**Comment by marcbachmann** [comment]
I've added that in the newest version
