### ISSUE TITLE
Bootstrap columns problem

### ISSUE THREAD

**Issue by simon-dube** [marcbachmann/node-html-pdf#25]
Hi, I am trying to generate my PDF layout using bootstrap columns classes, but it doesn't work. Each row takes a full line. I was simply wondering if anyone ran into this before and how they solved the issue.

Here is my code:
![image](https://cloud.githubusercontent.com/assets/10710692/7227467/3797f698-e751-11e4-85de-8b0335bcd9ee.png)

![image](https://cloud.githubusercontent.com/assets/10710692/7227436/e9b677ce-e750-11e4-9c71-b1bffad267fe.png)

Thanks.

**Comment by Uminily** [comment]
Try "col-xs-4" and "col-xs-8" :)

**Comment by simon-dube** [comment]
Thanks a lot! I had forgotten about the different prefixes.
