### ISSUE TITLE
Is there any way to pause for a number of seconds after onLoadFinished() before calling page.render?

### ISSUE THREAD

**Issue by chriskinsman** [marcbachmann/node-html-pdf#256]
We have some content that is not all rendered by the time onLoadFinished fires.  Need to add a delay. 

Thanks!

**Comment by marcbachmann** [comment]
sth like that? https://github.com/marcbachmann/node-html-pdf/pull/257
I don't like it because it adds a delay to every render call.

**Comment by chriskinsman** [comment]
Didn't see the other fork.  I created one that I will send a pull request for that uses a 0 delay when not specified that is working good for me.
