### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by itajaja** [marcbachmann/node-html-pdf#26]
simply
````
<a href="http://google.com">This is a link</a>
````
doesn't seem to work. The link is text is blue, but the cursor doesn't change when hovered, and it's not possible to click it. What could be the problem?

**Comment by itajaja** [comment]
worth mentioning I am on windows maybe :)

**Comment by itajaja** [comment]
I answer myself: not supported n phantomjs yet: https://github.com/ariya/phantomjs/issues/10196

**Comment by marcbachmann** [comment]
That's supported now in `html-pdf@2.0.0`

**Comment by shivam-ahuja** [comment]
still not working
