### ISSUE TITLE
External CSS file in header and footer

### ISSUE THREAD

**Issue by simon-dube** [marcbachmann/node-html-pdf#27]
I am trying to use en external CSS file in my header and my footer, but it doesn't seems to works. Even bootstrap style that works in the body doesn't work in footer and header. However, the inline CSS works, but I would prefer to have cleaner code and to split the CSS from the HTML.

Thanks.

**Comment by itajaja** [comment]
it doesn't appear to be supported at the moment. What I did, was to use [cheerio](https://github.com/cheeriojs/cheerio) to grab all the `link` element, resolve them, and wrap the resolved style inside a `<style></style>` tag. Be also aware that for now the only style that is grabbed for the header and footer is **the first one** declared. I am going to open a PR to solve that

**Comment by itajaja** [comment]
You can use [this PR](https://github.com/marcbachmann/node-html-pdf/pull/31) to work around the issue :)

**Comment by marcbachmann** [comment]
This should work now with the newest version

**Comment by elgubenis** [comment]
doesn't work for me with the newest version, im referencing bootstrap remotely in the head with a link element.

```html
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
```
