### ISSUE TITLE
Use with browserify?

### ISSUE THREAD

**Issue by roccons** [marcbachmann/node-html-pdf#28]
I wonder if this module can run in browser via browserify

I'm trying with your example code and replacing the line
var fs = require('fs');
with
var fs = require('browserify-fs');
or with
var fs = require('brfs');

but I always gey the same error
TypeError: fs.readFileSync is not a function

**Comment by marcbachmann** [comment]
Sorry, that's not possible. This library relies on phantomjs which won't run in the browser.

**Comment by roccons** [comment]
Thanks for the fast reply!
