### ISSUE TITLE
Japanese Text is not displayed

### ISSUE THREAD

**Issue by sasankamourya** [marcbachmann/node-html-pdf#290]
There is japanese text and english in my html. But when i convert it to pdf the japanese text is not printed. Is there any option to add something like UTF-8 in options? @marcbachmann

**Comment by frank-orellana** [comment]
Are you reading your HTML file with the right encoding? :

```js
const html = fs.readFileSync(inputFile, 'utf8');
```

**Comment by sasankamourya** [comment]
Hey! Problem Solved. Turns out that japanese fonts are not installed in linux by default. That is the reason why japanese text was not being displayed. To install Japnese fonts go to the following path:
#cd /usr/share/fonts
Then install the font from the below path:
# apt-get install fonts-takao-mincho 
To install more fonts:
# apt-get install fonts-takao
@frank-orellana @marcbachmann
