### ISSUE TITLE
How to use {{pages}} in body?

### ISSUE THREAD

**Issue by sblantipodi** [marcbachmann/node-html-pdf#293]
As title.
I can use {{pages}} to display the number of the PDF pages in footer.

It doesn't work if I put {{pages}} in the body.

Is there a solution to print the number of pages inside the body?

**Comment by IraErshova** [comment]
The same issue. If I want use page in html file, not in config.

**Comment by marcbachmann** [comment]
That won't work. In phantomjs pages don't have any context to their page number AFAIK.
