### ISSUE TITLE
Node 'fs' and 'child_process' packages are deprecated

### ISSUE THREAD

**Issue by kivohin** [marcbachmann/node-html-pdf#305]
Node 'fs' and 'child_process' packages are deprecated, and will give error in 'html-pdf/lib/pdf.js' file. It will never find those 2 packages. I tried both with npm install and yarn install, but I can't never make your package to work 😕

You can use instead 'node-fs' package, and for 'child-process' check this, maybe helps:
- https://nodejs.org/api/child_process.html

<img width="725" alt="screen shot 2017-07-12 at 10 48 05 am" src="https://user-images.githubusercontent.com/17774060/28123820-f7f368f8-66ef-11e7-951e-a2b62e9e5a36.png">

**Comment by marcbachmann** [comment]
Those are node modules and they are available in core. In case you're trying to bundle that module in the browser, that won't work. This module depends on phantomjs which is a binary executable.

**Comment by kivohin** [comment]
I see, thank you for your answer :+1:
