### ISSUE TITLE
Module not found: Can't resolve 'child_process' in '/Users/dorkblue/code/dorkblue/pdf-generator/no de_modules/html-pdf/lib'

### ISSUE THREAD

**Issue by dorkblue** [marcbachmann/node-html-pdf#307]
Tried the following

import * as pdf from 'html-pdf'
const pdf = require('html-pdf')

Any ideas how to solve this?

Using create-react-app to build react front end

**Comment by marcbachmann** [comment]
This module only works in node... the backend.

**Comment by dorkblue** [comment]
Yup i realized that! Thanks!

**Comment by atleugim** [comment]
I'm trying to use it in **Next JS** inside **getInitialProps** like this, but get this error:

error - ./node_modules/html-pdf/lib/pdf.js:2:0
Module not found: Can't resolve 'child_process'

`const isServer = !!req
  if (isServer) {
    const buffer = await pdfHelper.componentToPDFBuffer(
      <PDFLayout><Template data={data} /></PDFLayout>
    )
    res.setHeader('Content-disposition', 'attachment; filename="certificado.pdf')
    res.setHeader('Content-Type', 'application/pdf')
    res.end(buffer)
  }`
