### ISSUE TITLE
Can this work with chart.js?

### ISSUE THREAD

**Issue by adman020** [marcbachmann/node-html-pdf#312]
I'm trying to get piecharts to render in the report i'm building. Presently it's just showing blank. Is there a a way to delay a few milliseconds after the charts are produced?

**Comment by chuabingquan** [comment]
Hi, I recently used html-pdf with a HTML file with chartjs and I got it working. In particular, you can try to disable animations to prevent half rendered charts and adjusting for a longer timeout for phantomjs to allow your chart to fully render.

For a blank chart, my issue was uncaught javascript errors or using some ES6 syntax, hence, you might want to look into that.

You can refer to my code:
https://gist.github.com/chuabingquan/9827a3eb09cd4a2e27cf95dff7f09176

I need to have dinner now, will get back to you if you have any issues!

**Comment by shivamjain1210** [comment]
I have been trying to include the highcharts in the pdf and I was also getting the same issue(i.e. half rendered charts).
Is there a way to include the timeout so that the scripts will be rendered before the pdf is getting created.

**Comment by marcbachmann** [comment]
There's a `renderDelay` option in v2.2.0.

**Comment by marcbachmann** [comment]
You can also trigger the render manually if you set `renderDelay` to `manual`
Like in https://github.com/marcbachmann/node-html-pdf/blob/master/test/callback.html
https://github.com/marcbachmann/node-html-pdf/blob/master/test/index.js#L93

**Comment by lakshminarasimhan93** [comment]
> Hi, I got this module to work with my HTML with Chart.js and common issues and fix would include disabling your chart animations to prevent half rendered charts and extending the timeout of phantomjs.
> 
> With respect to getting a blank chart, my issue is usually caused by uncaught javascript errors or the using of some ES6 syntax such as template literals, hence, you might want to look into that.
> 
> You can refer to my code:
> https://gist.github.com/chuabingquan/9827a3eb09cd4a2e27cf95dff7f09176

Still im unable to render charts in generated . can some one guide me ? I have tried renderingDelay also .
