### ISSUE TITLE
Stream pdf to a URL 

### ISSUE THREAD

**Issue by vivekiyer114** [marcbachmann/node-html-pdf#313]
How can i stream the pdf to a url so that users are able to download it via browsers ?

**Comment by artemgrygor** [comment]
@vivekiyer114 this works for me:

        `let tmpl = fs.readFileSync('./views/exporttopdf.html', 'utf8');
        let compiled = _.template(tmpl);
        let html = compiled(data);
        pdf.create(html).toStream((err, stream) => {

            res.setHeader('Content-disposition', 'inline; filename="Test.pdf"');
            res.setHeader('Content-type', 'application/pdf');

            stream.pipe(res);
        });`

**Comment by starcraft0429** [comment]
I can receive string like below
```
%PDF-1.4
1 0 obj
<<
/Title (��)
/Creator (��)
/Producer (��
...
...
```
how can I show it in new browser tab

**Comment by marcbachmann** [comment]
Don't set the `Content-Disposition` header. Just the `Content-Type`.

```
const fs = require('fs')
const http = require('http')
const pdf = require('../../')

const server = http.createServer(function (req, res) {
  const html = `<html><body>Test</body></html>`
  pdf.create(html).toStream((err, stream) => {
    if (err) return res.end(err.stack)
    res.setHeader('Content-type', 'application/pdf')
    console.log(stream)
    stream.pipe(res)
  })
})

server.listen(8080, function (err) {
  if (err) throw err
  console.log('Listening on http://localhost:%s', server.address().port)
})
```

**Comment by marcbachmann** [comment]
I've added an example to https://github.com/marcbachmann/node-html-pdf/blob/master/examples/serve-http/index.js

**Comment by apmcodes** [comment]
The below doesn't work, still getting

```
PDF-1.4↵1 0 obj↵<<↵/Title (��)↵/
```

```
                htmlPdf.create(html).toStream((err, stream) => {
                    if (err) return next(err);
                    res.setHeader('Content-type', 'application/pdf');
                    stream.pipe(res);
                });
```
