### ISSUE TITLE
Using this library inside a nodejs application is 2x times faster than using it in the command line

### ISSUE THREAD

**Issue by acrolink** [marcbachmann/node-html-pdf#335]
Is this expected behavior?

**Comment by frank-orellana** [comment]
When you use it from the command line Node itself has to start before executing the script, so if you are using it inside Node, you are saved from that load time and it should be noticeable faster, so yes I guess it is something to be expected.

**Comment by acrolink** [comment]
@frank-orellana , thank you very much for the explanation.

**Comment by marcbachmann** [comment]
The new script probably has gotten faster in v2.2.0 (released yesterday).
I've changed some teardown behavior in there.

**Comment by acrolink** [comment]
@marcbachmann , not probably. I have just ran some tests and observed a 10% speed improvement with latest release, some `0.4` second faster when converting a 200 pages `html` to `pdf`. thank you very much.
