### ISSUE TITLE
'.'  in url changes the fileformat. 

### ISSUE THREAD

**Issue by vivekiyer114** [marcbachmann/node-html-pdf#337]
I have a route in my application : -
'/download2/firstname.lastname.refcode'

Here is a code snippet , 
```
var options = {format:'A4',border:{top:'20px',bottom:'20px'},type:'pdf'}
pdf.create(html,options).toBuffer(function(err, buffer){
		res.type('application/pdf');
		res.end(buffer, 'binary');
});
```
The '.' in the url changes the fileformat to '.refcode'. 
I also passed " type:'pdf' " in the options 

Any solution ?

**Comment by marcbachmann** [comment]
What browser do you use?
Here's an example how to serve the pdf using a web server. Can you test that?
Just use your url. That should work, at least on chrome.
https://github.com/marcbachmann/node-html-pdf/blob/master/examples/serve-http/index.js

**Comment by vivekiyer114** [comment]
I used the header :-
Content-dispostion: inline; 'filenamr.pdf' 
where filename can be anything. 

Above line solved the issue

**Comment by marcbachmann** [comment]
To be a bit more specific, according to the [spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_response_header_for_the_main_body), you should use the `filename` directive.

```
Content-Disposition: inline; filename="firstname.lastname.refcode.png"
```

You could also replace `inline` with `attachment` to force a download.
MDN is always a good reference ;)

**Comment by vivekiyer114** [comment]
Oh...yes  
Thank you very much
