### ISSUE TITLE
Is there any solution for React project?

### ISSUE THREAD

**Issue by starcraft0429** [marcbachmann/node-html-pdf#338]
Thanks for this package.
I want to use this package in React project.
but there is 
`
Module not found: Can't resolve 'fs', 'child_process', etc
`

How can I use this in React project?

**Comment by marcbachmann** [comment]
Sorry, this module doesn't work client-side.
So you'll have to do a request to a server.

**Comment by starcraft0429** [comment]
Thanks. got it

**Comment by starcraft0429** [comment]
I made request to node backend from React.
I want to see pdf after ajax request in new tab.
currently I can receive butter as string 
```
%PDF-1.4
1 0 obj
...
23658
%%EOF
```
but I want to see generated pdf file in new tab.
would you give me idea?
