### ISSUE TITLE
example files links are broken

### ISSUE THREAD

**Issue by Sergeon** [marcbachmann/node-html-pdf#345]
The links from the [npm package page](https://www.npmjs.com/package/html-pdf) and the [readme page](https://github.com/marcbachmann/node-html-pdf) are broken:
https://github.com/marcbachmann/node-html-pdf/blob/HEAD/examples/businesscard.pdf
https://github.com/marcbachmann/node-html-pdf/blob/HEAD/examples/businesscard.html

An extra 'businesscard' segment is needed, like:
https://github.com/marcbachmann/node-html-pdf/blob/HEAD/examples/businesscard/businesscard.html

However, it doesn't seem to be any `.pdf` file under `examples/businesscard`.  Maybe something went wrong in [the last commit](https://github.com/marcbachmann/node-html-pdf/commit/f5fe1911f1683772190fb0b3bb42432b3f56cc77) ?

**Comment by marcbachmann** [comment]
Oh yeah, sorry, I just moved the examples into subdirectories. The example pdf needs to be regenerated. I’d split up the test file and move them into the examples directory.

**Comment by Sergeon** [comment]
This is fixed now by [#63ba98](https://github.com/marcbachmann/node-html-pdf/commit/63ba98f63b0fc178290415b0585b52db0190aeca), thanks!
