### ISSUE TITLE
Very large file sizes - any tips for reducing?

### ISSUE THREAD

**Issue by jeznag** [marcbachmann/node-html-pdf#351]
Hi, I'm converting a simple six page HTML document which is 95% text with a small PNG logo. When I run html-pdf on my mac, it works perfectly and generates a 68kb PDF. However, when I deploy it to Heroku, I get a 6MB monster of a file. Any tips for reducing the file size? 

I'm using 
```
       {
          border: {
            bottom: '30px',
            top: '50px'
          },
          quality: 40
        }
```
as my options.

**Comment by marcbachmann** [comment]
The reason for the large file is most likely the fonts.
There's an issue that discussed that topic: https://github.com/marcbachmann/node-html-pdf/issues/151

**Comment by jeznag** [comment]
Amazing! I changed to a standard font and it's down to 55kb :) Can we have something in the README to help people with this?

**Comment by marcbachmann** [comment]
Yeah, we should put that into some a know issues or FAQ section.
I began with tagging some issues a while ago: https://github.com/marcbachmann/node-html-pdf/labels/faq
