### ISSUE TITLE
Table headers get copied

### ISSUE THREAD

**Issue by bramschulting** [marcbachmann/node-html-pdf#36]
### Reproduction
1. Create a PDF from HTML containing a table that overflows onto the next page

### Current behaviour
The table headers gets rendered twice, overlapping the table body.

### Expected behaviour
The header only gets rendered once.

### Files and screenshots
[Here](http://cl.ly/0G1j1i3y1V2t) you can find the actual PDF, but the following screenshot shows the problem as well:

![screen shot 2015-06-07 at 23 53 25](https://cloud.githubusercontent.com/assets/1703323/8026277/67d7b18c-0d70-11e5-9b6b-1b6b5744b539.png)

**Comment by marcbachmann** [comment]
The repeating table header is the expected behavior. Although the style is  a bit strange. I guess if you want to disable that, you can add the css `thead {display: block}` or don't use thead.

**Comment by bramschulting** [comment]
Thanks, but when I add `thead {display: block}`, the head looks like this.
![screen shot 2015-06-09 at 23 41 16](https://cloud.githubusercontent.com/assets/1703323/8070404/26538a8c-0f01-11e5-91c2-ff3c8e50f107.png)

Leaving out the thead is not really an option for me. Are there any other options?

**Comment by marcbachmann** [comment]
Oh, yeah, you have to use `display: table-row-group`. Sadly there's no other solution except altering the dom using js  (or patching QT), which I wouldn't do.

**Comment by bramschulting** [comment]
Worked perfectly! Thank you!
