### ISSUE TITLE
CentOS text does not render

### ISSUE THREAD

**Issue by strunkie30** [marcbachmann/node-html-pdf#37]
I try to make a PDF with but my fonts does not render.
All my pdf's looks like this: http://kevinmeijer.com/html-pdf-9072.pdf

I'am on CentOS 6.

**Comment by strunkie30** [comment]
Solved by install system fonts.

**Comment by SFantasy** [comment]
@strunkie30 Hi, I'm using this module and got the same question as you mentioned.

I'm not clear about "install system fonts", is that meaning that I should install fonts using in my HTML file on my server(CentOS)?

**Comment by strunkie30** [comment]
The PDF printer can't print your document because a clean CentOS installation does not include fonts.
Windows and OSx has by default system fonts: https://en.wikipedia.org/wiki/List_of_typefaces_included_with_OS_X

You can find multiple fontpacks on the internet for CentOS:
http://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-install-microsoft-truetype-fonts-in-centos-6-rhel-6.html#axzz3hGwfK1Gw

If you are custom fonts from Google fonts or Typekit you can append them normaly, your fonts will be rendered fine. But Arial does not exists on CentOS.

Sorry for my bad english :smile:

**Comment by marcbachmann** [comment]
@strunkie30 thanks for answering

**Comment by SFantasy** [comment]
@strunkie30 

Thanks,  I've solve the problem by

```sh
yum install cjkuni-ukai-fonts 
```

Although the fonts looks a little strange, maybe I should find another fonts :smiley:

**Comment by marcbachmann** [comment]
There's an install script for microsoft fonts:
https://github.com/marcbachmann/dockerfile-phantomjs2/blob/master/Dockerfile#L4-L7
