### ISSUE TITLE
The settings for the size of the PDF file do not work on Linux

### ISSUE THREAD

**Issue by Bleser92** [marcbachmann/node-html-pdf#375]
OS: Ubuntu server 16.04 x64
html-pdf: v2.2.0

When forming a file, it is formed on the right. This is observed only on Linux, on Windows the size corresponds to what is registered in the settings.

![default](https://user-images.githubusercontent.com/12870298/34106149-eb7de19c-e418-11e7-8a74-09bf0f1f3822.png)

```typescript
pdf.create(html, {
    // format: isKv ? "Tabloid" : "A4", // true
    width:"11in",
    height:"17in"
}).toFile(path.resolve(process.cwd(), filePath + ".pdf"), (err, res) => {
    if (err) return console.log(err)
    console.log(res)
})
```

**Comment by Spymannn** [comment]
Hi, 

I have the same issue here, working well on windows but not on Ubuntu.
That's weird.

Any news about it ?

**Comment by marcbachmann** [comment]
Yes, that's an annoying issue of phantomjs. Please check out https://github.com/marcbachmann/node-html-pdf/issues/198 for more details.

**Comment by Bleser92** [comment]
@Spymannn I used a little trick to get the result I needed.
```typescript
pdf.create(html, {
	format: "A2",
	border: "2cm"
} as any).toFile(...)
```
@marcbachmann Thanks for the solution of this problem.

If there are no more questions left, can I close this question?

**Comment by Spymannn** [comment]
Same here, I could fixed it by using 
`const options = { format: 'A4', width:"11in", height:"17in" };
				pdf.create(html, options)`

It works well now.

Thanks @Bleser92 and @marcbachmann 

You can close this issue
