### ISSUE TITLE
When executing code through this error ?

### ISSUE THREAD

**Issue by bgobi1991** [marcbachmann/node-html-pdf#38]
My code :+1: 
```js
var fs = require('fs');
    var pdf = require('html-pdf');
    var html = fs.readFileSync('./test/businesscard.html', 'utf8')
    var options = { filename: './businesscard.pdf', format: 'Letter', width: '210mm', height: '297mm', border: '10mm', timeout: 30000 };
    pdf.create(html, options, function(err, buffer) {
      if (err) return console.log(err);
      console.log("Converted successfully. Output in " + outputPath);
    });
```
```
[Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.]
```

**Comment by marcbachmann** [comment]
What system are you on? what's your  cpu & ram?

**Comment by bgobi1991** [comment]
![system info](https://cloud.githubusercontent.com/assets/9972138/8123572/c3b55b0e-10e9-11e5-9fbc-b6b9bfa9c768.png)

**Comment by marcbachmann** [comment]
Can you try to use the newest version and increase the timeout? I had a 2 minute timeout in the phantomjs script.

**Comment by bgobi1991** [comment]
working fine for 2 mins timeout but this took much time to load. user not wait for 2 mins to load page.

**Comment by bgobi1991** [comment]
thanks a lot, working fine right now. i have one doubt when creating a pdf, is possible for download automatically ?

**Comment by marcbachmann** [comment]
You can use `content disposition` to automatically download a file from a server.

**Comment by marcbachmann** [comment]
On my webserver it only takes a few seconds (~3s) to create a pdf. Looks like on windows it's much slower.
