### ISSUE TITLE
Pdf do not show any word, only css

### ISSUE THREAD

**Issue by 89466598946659** [marcbachmann/node-html-pdf#381]
RT, when pdf.create(html).toBuffer, the pdf do not show any word, include number and chinese, only show css & img. Do I have something wrong? Or lack someth package?

**Comment by 89466598946659** [comment]
Ok, I know. Installed urw-fonts and msyh.ttf.

**Comment by MuthukumarHelios** [comment]
Can i Have your Source code So that I can Reproduce # @89466598946659

**Comment by 89466598946659** [comment]
@MuthukumarHelios  The reason is I lack some package about number and chinese. When I done this, it works.

**Comment by MuthukumarHelios** [comment]
Nice If your Issue get's Solved You can close your Issue  will help the community
