### ISSUE TITLE
html-pdf not reading the Image which is on the css attribute

### ISSUE THREAD

**Issue by MuthukumarHelios** [marcbachmann/node-html-pdf#382]
[see issue 44](https://github.com/marcbachmann/node-html-pdf/issues/44)  --> Might be same question

Working fine in the normal Browser but not in after generating the pdf
`compiledhtml = <body style='background:url("/Images/certificate_background.jpg")'>`

---------------------------------------------------------
working in both the browser the pdf 
`compiled html = <img src = "/Images/certificate_background.jpg"> 
`

>issue 
Stand alone rendering html tags working fine but not With css 
But other background styles is working fine after generating the pdf

```js
                
                let options = {
                    "format": 'Letter',
                    "base": http://localhost:3000   --> My static expressjs server
                };       
 

pdf.create(compiledHtml, options).toFile(pdfFileName, (err, response) => {
                 res.json(response)
                 }
```
The below link is the Bootstrap local cdn
Version Bootstrap v3.3.7
```<link href="/bootstrap/css/bootstrap.css" rel="stylesheet">```
If I am Removing the Above bootstrap it works fine for the Background image 
``body{
background-image : "https://imageurl.png"
}``

**Comment by MuthukumarHelios** [comment]
There is the problem with the css while compiling my html 
!important fixed my issue
`<body style='background: url("/Images/certificate_background_gif.jpg") no-repeat !important; background-size:100% 100% !important;'> 
`

**Comment by theyeshu** [comment]
Adding base works for me. To making base dynamic I use following.

``base: `${req.protocol}://${req.get('host')}`,``
