### ISSUE TITLE
Node JS Html-pdf : create different header footer for first and last page

### ISSUE THREAD

**Issue by raviguptaa3** [marcbachmann/node-html-pdf#390]
I am new in node js, and I want to use different header and footer for first and last pages in node js,

I am using html-pdf module which is not working when I use the same code as they have provided.

please have a look into the code

```
var fs = require('fs');
var pdf = require('html-pdf');
var html = fs.readFileSync('test.html', 'utf8');
var options = { format: 'Letter' };

pdf.create(html, options).toFile('businesscard.pdf', function(err, res) {
  if (err) return console.log(err);
  console.log(res); // { filename: '/app/businesscard.pdf' }
});
```

When I am using below code It will not work on the last page only It also print for middles pages.

```
<div id="pageHeader-last">Header on last page</div>
...
<div id="pageFooter-last">Footer on last page</div>
```

**Comment by abhinava3** [comment]
Hi ravi , It is working in the html-pdf version 2.1.0
you can install it via npm install html-pdf@2.1.0

**Comment by raviguptaa3** [comment]
thanks @abhinava3  it is working!!

**Comment by jitendarkumars** [comment]
Hi, 
I'm facing an issue that when I make a header of fixed length, then on First page the header occupies more space than other pages. There is additional margin at the top of page. How can I remove it.

**Comment by jitendarkumars** [comment]
[filename (38).pdf](https://github.com/marcbachmann/node-html-pdf/files/2487373/filename.38.pdf)

**Comment by shaileshrajaram** [comment]
> Hi ravi , It is working in the html-pdf version 2.1.0
> you can install it via npm install html-pdf@2.1.0

thank you
