### ISSUE TITLE
execute node filename programatically is a problem

### ISSUE THREAD

**Issue by Amara-Balakrishna1** [marcbachmann/node-html-pdf#42]
```js
var fs = require('fs');
var pdf = require('html-pdf'); 
var options = { filename: 'businesscard.pdf', format: 'Letter' }; 
  console.log("sadfasdf")
console.log(html="<body><div style='background-color: #000088' >dfasdf</div><table></table><td>fsdafsdf</table></body>")
pdf.create(html, options).toFile(function(err, res) {
    if (err) return console.log(err);
    console.log(res); // { filename: '/tmp/html-pdf-8ymPV.pdf' }
}); 
```
if my code has more content oh the same line new line automatically not getting inserted.

**Comment by marcbachmann** [comment]
I don't understand your problem. Is this related to this comment I just made here? https://github.com/marcbachmann/node-html-pdf/commit/3ea3cc3412396ef3ee85cfb83cdb9f45187b7e05

**Comment by Amara-Balakrishna1** [comment]
thank you for ur replay my problem is if a line has 300 chars and generated pdf can show only 150 chars. new line is not attaching dynamically when num of chars exceede the 150.how can we show if there are 300 chars in line1 of my file.html -> 0 to 150 chars in line1 of pdf and 150 to 300 chars at line 2 of our pdf.so that no info is missing.
