### ISSUE TITLE
CSS gradient not rendered

### ISSUE THREAD

**Issue by dannyfabricant** [marcbachmann/node-html-pdf#431]
`-webkit-linear-gradient(-30deg, #F8B298, #FFEDBF)` is rendered in the browser but not in the exported pdf.

**Comment by marcbachmann** [comment]
Please post your fix in here if you close something.
What was your workaround? Did you use autoprefixer? https://github.com/postcss/autoprefixer

**Comment by cfaure004** [comment]
` background-image: conic-gradient( #00acc1 72deg, #999999 72deg,  #999999 234deg, #ff9800 0 ) !important;` is also rendered in the browser but not in the exported pdf.

How did you solve this problem ?

**Comment by uzarsalan** [comment]
Hi! Did you solve this issue?

**Comment by kfmdm** [comment]
Hey can someone please post the solution ?
