### ISSUE TITLE
Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2

### ISSUE THREAD

**Issue by Messilimeng** [marcbachmann/node-html-pdf#435]
![image](https://user-images.githubusercontent.com/12272166/40893558-a1eb3634-67d4-11e8-92d2-b2be1b485061.png)

**Comment by Asreepathi** [comment]
I am facing the same issue,  please help

**Comment by Messilimeng** [comment]
@Asreepathi i am sorry i forgot how to fix that

**Comment by HBF1** [comment]
run command
yum install bzip2

its works

**Comment by nabajitroy** [comment]
Gr8 -yum install bzip2 worked for me

**Comment by henimbola** [comment]
Installing bzip2 also worked for me.

**Comment by Heriberto-Juarez** [comment]
> Gr8 -yum install bzip2 worked for me

In my case I am running ubuntu and it worked too:

sudo apt install bzip2

**Comment by abelaneiros** [comment]
Same fix for WSL2/Ubuntu still valid
`sudo apt install bzip2`
