### ISSUE TITLE
Custom font and very big result PDF on server

### ISSUE THREAD

**Issue by lukasamd** [marcbachmann/node-html-pdf#439]
Hello,
I would like to use custom font in my PDF. First tried use base - locally (OSX) works perfectly, but it doesn't work on server (Ubuntu 16.04). Then changed url to hostname. It works fine now, but result PDF file is very big (30 MB). When I use the same code locally using base, file has only about 180 KB.

**Comment by vikaschandra123** [comment]
Hello,
I am also facing the same issue. The resulted pdf generated from windows works fine but when it is run from ubuntu it increases the size of font which makes it overflow the page. There is no provision to custom set the font size.

**Comment by lukasamd** [comment]
The file is huge because there is no text, but all pages as images.
But why... don't know.

**Comment by lukasamd** [comment]
I think I found solution - I installed fonts locally on server instead of using font-face with url in CSS and base on PDF settings. Now it's works very fast and file is real PDF with text.
