### ISSUE TITLE
Failed to load PDF on aws lambda

### ISSUE THREAD

**Issue by KrifaYounes** [marcbachmann/node-html-pdf#460]
when I try to load my pdf with a lambda endpoint on aws I get this error : 
Failed to load the PDF document.

Everything is ok : response status : 200
content : application/pdf

My lambda works fine in offline mode 
I have used serverless to deploy my lambda with serverless-webpack to bundle project 
thanks

**Comment by olaftactech** [comment]
Do u found some solution? @KrifaYounes

**Comment by KrifaYounes** [comment]
yes I found a solution
you should authorize application/pdf on apigateway confirguration

**Comment by olaftactech** [comment]
Thanks too much @KrifaYounes !!

**Comment by Satendra-dev** [comment]
@KrifaYounes .. not sure if you are still active but I have ended up with the same problem as yours. Wondering if you could help me?
My lambda code is as below. I also tried to add Binary Media Types in API Settings but didn't work. 
My lambad here is proxy integration.
return {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': 'attachment; filename=site-plan.pdf',
        'Access-Control-Allow-Origin': '*'
      },
      statusCode: 200,
      body: pdf.toString('base64'),
      isBase64Encoded: true
    }

**Comment by thani21** [comment]
you should authorize application/pdf on apigateway confirguration
