### ISSUE TITLE
running in local it works fine but after hosting means in production the font size is increasing 

### ISSUE THREAD

**Issue by Rishabhqleverlabs** [marcbachmann/node-html-pdf#465]

**Comment by Fujiwaranosai** [comment]
Hi, did you find any solution? I'm facing the same problem now.

**Comment by dfloratos** [comment]
As someone also mentioned:
```
html{
zoom:0.6;
}
```
the number 0.6 in my case was 0.75

**Comment by lakshminarasimhan93** [comment]
me too facing this issue . Does anyone solved this before ? @marcbachmann

**Comment by AlejoMedina98** [comment]
@Rishabhqleverlabs  did you find a solution for this ?

**Comment by WouTripTeam** [comment]
me to

**Comment by shubhamappstec** [comment]
I have also same issues.. please suggest me somthing

**Comment by ELBEQQAL94** [comment]
I have also same issues :)

**Comment by rohitkhatri** [comment]
Hey @Rishabhqleverlabs, were you able to find solution for this?

**Comment by Fujiwaranosai** [comment]
The solution that worked for me is to use `zoom: 0.7;` on the `<html>`. Just adjust the zoom value to what you want. You may also need to use the latest phantomjs although it is deprecated now so you need to find an alternative and maybe it will fix the issue without having to update the `zoom`
