### ISSUE TITLE
how to pass data from node.js to html file for printing pdf

### ISSUE THREAD

**Issue by bapatel1** [marcbachmann/node-html-pdf#47]
I have created https://github.com/bapatel1/node-html-pdf-sample  with your lib and using angular.js in html. Now my problem is , I have to send filtered data to display from node.js to html file to generate pdf from that. (Kind of like html is template and pass data from node.js )

Any idea how may i achieve that, really appreciate your help in this matter as have release in near future.
Thank you

**Comment by bapatel1** [comment]
@marcbachmann 
just for an example - 

 var data = {
        ticketNum : 12121212,
        dateIssued: '2014-04-02',
        personName: 'John Doe',
        notes:' Lorem Ipsum Lorem ipsum dolor sit amet, consectetur adipiscing'
    };

    //TODO: pass this data object json to html to print this data.

    pdf.create(html,report_options).toStream(function(err, stream){
        console.log(stream);
        stream.pipe(res);
    });

**Comment by marcbachmann** [comment]
Ah, that's not the job of this library. You can use some template language to generate your html.
All template languages in node give you a `.render` method that output the html rendered with the `locals`.
load template -> render using data -> html-pdf

**Comment by marcbachmann** [comment]
Something like this:
```
var nunjucks = require('nunjucks')
nunjucks.configure(__dirname+'/views')
html = nunjucks.render('template.html', foo)
htmlPdf.render(html, options).toStream(function...)
```

**Comment by bapatel1** [comment]
@marcbachmann  Oh I see now. I guess i am still trying to understand node better and I appreciate your help in this query. I will give it a try now and will post here.
thank you,

**Comment by marcbachmann** [comment]
you're welcome

**Comment by bapatel1** [comment]
@marcbachmann You saved me .. nunjucks worked for me like a charm and pdf is also generating using your lib. I have updated my sample code with some more node.js clustering support. 
https://github.com/bapatel1/node-html-pdf-sample
Thank you once again.

**Comment by bapatel1** [comment]
Closing issue with solution which @marcbachmann  suggested as above. Using template engine called "nunjucks" worked for me.

**Comment by Lichtjaeger** [comment]
I prefer Jade. Works the same, but is more “stylish”.
