### ISSUE TITLE
single page pdf

### ISSUE THREAD

**Issue by refaelos** [marcbachmann/node-html-pdf#48]
Hey,

Is it possible to do a single page pdf?

Thanks!

**Comment by bapatel1** [comment]
Not sure what is the scope your tasks but you can check https://github.com/bapatel1/node-html-pdf-sample which i've created using this node-html-pdf library.

**Comment by marcbachmann** [comment]
Hi, saving a pdf currently only works with a fixed page size. But I guess we can also recognize the paper size based on the html body height and width. But that doesn't work with every html/css, thus might be a bit complicated.

**Comment by refaelos** [comment]
Too bad ... I'll see what I can do here with what I have.

Thanks!
