### ISSUE TITLE
[Error: PDF creation timeout. PDF generation script did not end.]

### ISSUE THREAD

**Issue by mpkorstanje** [marcbachmann/node-html-pdf#5]
On Windows 7 when trying to convert a .html to .pdf I get this message: `[Error: PDF creation timeout. PDF generation script did not end.].` and no .pdf.

Script

```
var fs = require('fs');
var pdf = require('html-pdf');
var html = fs.readFileSync('LICENSE.md.html', 'utf8')
pdf.create(html, { width: '50mm', height: '90mm'}, function(err, buffer) {
  if (err) return console.log(err);
  fs.writeFile('LICENSE.md.html.pdf', buffer);
});
```

LICENSE.md.html

```
<p>Copyright (c) 2014 GitHub Inc.</p>
```

Note: Originally discovered the issue in the [markdown-pdf](https://github.com/travs/markdown-pdf/issues/7#issuecomment-63857322) module for Atom.

**Comment by MisterNice** [comment]
I'm sporadically receiving this error, which appears related to this thread:
[Error: html-pdf: PDF generation timeout. Phantom.js script did not exit.]
It worked just fine yesterday, not working today with no change in that part of my code. I'm on version 1.5.0

var html = ejs.renderFile(appRoot + '/path/to/file', {
                            var: var
                        }, function (err, result) {
                            if (result) {
                                html = result
                                console.log(html)
                                var options = {format: 'Letter'}                    
                                var filename = bcrypt.hashSync(jobInfo[0].customer)          
                                pdf.create(html, options).toFile(appRoot + '/public/uploads/invoices/WO-' + opID + "-" + filename + '.pdf', function(err, res){ 
do some other stuff
}
