### ISSUE TITLE
Crashes on mutli-node.js system

### ISSUE THREAD

**Issue by wkande** [marcbachmann/node-html-pdf#50]
Running the following on a single Node.js server is fine.

console.log('create PDF');
                            pdf.create(html).toBuffer(function(err, buffer){
                                //console.log('This is a buffer:', Buffer.isBuffer(buffer));
                                console.log('create PDF async call returned');
                                try{
                                    posterBuffer = buffer;
                                    callback();
                                }
                                catch (err){
                                    callback( err );
                                }
                            });

But if you have two servers behind an HAPROXY load balancer both servers crash with (no state):

****************** START ERROR********************
Un-Caught exception (reported from app.js): 
{ [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
****************** END ERROR ********************

I read a post about a double callback failure with phantom but now I cannot find it again.

Server OS Ubuntu 14.0.4
Node 12.5

**Comment by marcbachmann** [comment]
Hehe, the problem is gone?

**Comment by grsabreu** [comment]
@wkande the problem is gone?
how did you solve it?

**Comment by marcbachmann** [comment]
There was never a problem like this. EPIPE means that no phantomjs binary is present. So `npm install` failed somehow.

**Comment by grsabreu** [comment]
Oh, I solved it!
I just added phantomjs@1.9.16 in my project package.json and it worked.
@marcbachmann maybe you can replace "optionalDependencies" by "dependencies" node-html-pdf package.json to solve this problem.
