### ISSUE TITLE
Fontconfig warning: ignoring UTF-8: not a valid region tag : Ubuntu 14.04

### ISSUE THREAD

**Issue by safiresh** [marcbachmann/node-html-pdf#52]
Hi Team, 
when convert html to pdf i am getting this error . kindly give me correct solution. i tried lot ways from google . 
i belive this is phantomJS issue  on Ubuntu

**Comment by lonedune** [comment]
i've got this error message too

**Comment by marcbachmann** [comment]
Hmm. Sorry, I've never seen that error. Have you tried phantomjs2?

**Comment by lonedune** [comment]
mine's:

root@mean:/home# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by thakkarparth007** [comment]
@lonedune, can you tell what exactly you did to solve this issue? I've been facing it too.

**Comment by parthcanbrand** [comment]
I have fixed by adding these lines to /etc/environment
LANG=en_US.utf-8
LC_ALL=en_US.utf-8

**Comment by safiresh** [comment]
I fixed this issue set environment variable. 
sudo nano /etc/environment

#append below line 
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8


kindly restart env variable else log off and login onetime .

**Comment by safaorhan** [comment]
Facing the same issue on Ubuntu 14.04.

$ `env | grep LC` gives:

> LC_ALL=en_US.UTF-8
> LC_CTYPE=UTF-8

$ `locale` gives:
> LANG=en_US.UTF-8
> LANGUAGE=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=en_US.UTF-8

**Comment by dejankorez** [comment]
I have the same problem :(

**Comment by safiresh** [comment]
It's warning only. you can skip this.

**Comment by uber1geek** [comment]
This should fix your issue:

sudo apt-get install language-pack-en-base
sudo dpkg-reconfigure locales (Select All and then select en_us for local)
sudo reboot

**Comment by moschel26** [comment]
@uber1geek  Maybe you can help this question :  https://stackoverflow.com/questions/51947226/how-can-i-install-gitextensions-in-mac-os
