### ISSUE TITLE
Pdf 

### ISSUE THREAD

**Issue by angeltg83** [marcbachmann/node-html-pdf#521]
after executing my html with html-pdf version 2.2.0 it was deformed in the style, before I used html-pdf version 1.5 but updated it by the updated version of node v10.16.0

attack de file
[ODA.pdf](https://github.com/marcbachmann/node-html-pdf/files/3465126/ODA.pdf)

**Comment by Serhioromano** [comment]
Please make your title self explanatory.

**Comment by angeltg83** [comment]
yes, 
when I invoke the html-pdf function with the new version of the library, the resulting pdf is displayed outside the margins
!!

**Comment by angeltg83** [comment]
in the previous version of 1.5 it does not give that error and the resulting pdf is displayed correctly

**Comment by Serhioromano** [comment]
Add to HTML `<table style="max-width: 500px">`.

**Comment by angeltg83** [comment]
the solution is to modify the html source?

**Comment by Serhioromano** [comment]
Yes. I had the same problem with images. Those were clipped out. I added this style tag and it worked. I just replace HTML text before passing to create PDF

```js
while (str.match(/(<img src="\.\.\/)/ig)) {
    str = str.replace('<img src="../', `<img style="max-width:400px" src="../'}`);
}
```

**Comment by angeltg83** [comment]
It is a mistake that should be corrected, it cannot be that when updating the version the final pdf overflows even everything enlarges letters and margins and images.

please!!

**Comment by Serhioromano** [comment]
It is quite normal way to make adjustments to your document before conversion. Do not you expect to get HTML to PDF converter that simply convert into documents you immediately like? This does not exists. That is why this tool have parameters for borders, fonts, ....

**Comment by angeltg83** [comment]
ok..

**Comment by rubenheymans** [comment]
> It is quite normal way to make adjustments to your document before conversion. Do not you expect to get HTML to PDF converter that simply convert into documents you immediately like? This does not exists. That is why this tool have parameters for borders, fonts, ....

This does exist though, we can now generate pdf files in a headless chrome with puppeteer. It just takes your html page 1 on 1, no more pdf hell!
