### ISSUE TITLE
custom font not rendered

### ISSUE THREAD

**Issue by serhatleventyavas** [marcbachmann/node-html-pdf#551]
Hi everyone,

I have html template, like this
`<html>
    <head>
        <meta charset="utf8"/>
        <style>
            @font-face {
                font-family: "Arial";
                src: url("http://server_url/fonts/arial.ttf");
                font-weight: normal;
                font-style: normal;
            }

            @font-face {
                font-family: "Arial";
                src: url("http://server_url/fonts/ArialBold.ttf");
                font-weight: bold;
                font-style: normal;
            }

            @font-face {
                font-family: "Arial";
                src: url("http://server_url/fonts/ArialBoldItalic.ttf");
                font-style: italic;
                font-weight: bold;
            }

            @font-face {
                font-family: "Arial";
                src: url("http://server_url/fonts/ArialItalic.ttf");
                font-style: italic;
                font-weight: normal;
            }

            body {
                font-family: 'Arial';
            }
            #pageHeader { 
                height: 40px;
             } 
            #introductionContent { font-size: 11px;}
            #finalContent { font-size: 11px;}
            #infoTable td { font-size: 11px; }
            #itemTable td { font-size: 11px; }
            #itemTable tr { font-size: 11px; }
            #itemTable { border-spacing: 0px; }
            #itemTable thead tr th{border-bottom: 1px solid black; border-collapse:separate;}
            #itemTable thead tr th { padding: 10px; }
            #itemTable tbody tr td { padding: 10px; }
            #pageFooter { height: 60mm; font-size: 8px; }
            #senderTD {
                font-size: 8px !important;
            }
            #pageFooter p { font-size: 8px !important; }
            b {
                font-weight: bold;
            }
            strong { font-weight: bold; }
        </style>
    </head>
    <body>
        ...
    </body>
</html>`

When I open the html template in the browser, arial font is rendered but when I create a pdf, arial font is not rendered. where am i wrong? Where is the problem ?

thank you to everyone in advance

**Comment by andypopa** [comment]
The way I do it is I install the fonts on the server running the app.

I use Times New Roman, Arial on an Ubuntu 18.04 server.

You can install these fonts with 
`sudo apt-get --reinstall install ttf-mscorefonts-installer`
