### ISSUE TITLE
pdf not created html-pdf: PDF generation timeout. Phantom.js script did not exit.

### ISSUE THREAD

**Issue by ajinkyakadhe** [marcbachmann/node-html-pdf#566]
this npm working as expected on local host but it doesn't work as on local host after deploying cloud scheduler function  it gives me above error.i tried timeout upto 900000 it won't work for me. any work around or fixes?

**Comment by martisj** [comment]
A little more of your code might illuminate the issue. @ajinkyakadhe

**Comment by dhruvaprajapati** [comment]
@ajinkyakadhe Your one of the external css/js might have not loaded.

**Comment by ajinkyakadhe** [comment]
Thank you for your reply @dhruvaprajapati and @martisj... I resolved this problem using dividing load into two different parts..
