### ISSUE TITLE
License

### ISSUE THREAD

**Issue by agairing** [marcbachmann/node-html-pdf#59]
Hi,
can you please add a license agreement for your project?

Cheers,
Andreas

**Comment by marcbachmann** [comment]
Currently I have the license in the package.json
https://github.com/marcbachmann/node-html-pdf/blob/master/package.json#L13

**Comment by agairing** [comment]
Thank you for the quick answer.

**Comment by marcbachmann** [comment]
I can add the license if I have sometime
