### ISSUE TITLE
Is there a way to break the page intelligently based on the content?

### ISSUE THREAD

**Issue by sripaulgit** [marcbachmann/node-html-pdf#60]
Lets say I pass in a long html content and I would want to break the page at a particular meaningful spot, can i do that? Is there some parameter that i can leverage for it.

**Comment by marcbachmann** [comment]
There are the `page-break` css properties.
I've never used `page-break-inside: avoid;`, but that might be the one you can use. Probably you can apply it to the `p` tag or something else.
https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-after
https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-before
https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-inside

**Comment by marcbachmann** [comment]
See #49

**Comment by PanMan** [comment]
```` page-break-inside: avoid; ```` seems to be ignored. I read somewhere that it's supported in PhantomJS > 2.0, but the node module is on 1.9x

**Comment by molerat619** [comment]
any news?
