### ISSUE TITLE
html-pdf: Evaluation - ReferenceError: Can't find variable: Set

### ISSUE THREAD

**Issue by MazzMazz** [marcbachmann/node-html-pdf#626]
After running for months without problem we suddenly receive the following error message. Locally and on the live servers.

```
Server running on http://0.0.0.0:8080
Error: html-pdf: Unknown Error
html-pdf: Evaluation - ReferenceError: Can't find variable: Set
Stack:
  at https://static.cloudflareinsights.com/beacon.min.js
  at https://static.cloudflareinsights.com/beacon.min.js
  at https://static.cloudflareinsights.com/beacon.min.js
  at https://static.cloudflareinsights.com/beacon.min.js
  at https://static.cloudflareinsights.com/beacon.min.js

    at ChildProcess.respond (/pdf-printer/node_modules/html-pdf/lib/pdf.js:134:17)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)

```

Is something known about this?

We had Version 2.2.0 running - tried to update to Version 3.0.1 but the same problem occurs.

**Comment by MazzMazz** [comment]
I just found out that the Cloudflare Browser Insights is the Problem. Disabling this option will make the pdf generator work again. I guess they have an issue in their js file.

![image](https://user-images.githubusercontent.com/10706512/119971701-97b0e000-bfb1-11eb-8c39-a7cbcc515a7d.png)

**Comment by 42510SR** [comment]
@MazzMazz html-pdf: Received the exit code '1'\nhtml-pdf: Evaluation - ReferenceError: Can't find variable: $\nStack:\n  at undefined
 I am facing this issue while i am trying to create a pdf using pdf.create method from html-pdf library
