### ISSUE TITLE
Selectable and searchable text

### ISSUE THREAD

**Issue by medikoo** [marcbachmann/node-html-pdf#63]
I noticed that it generates whole PDF as image, and texts are neither selectable nor searchable.

Is there any option that can fix that. I know that having that with phantom is possible, as .e.g. http://www.html2pdf.it/ demonstrates

**Comment by marcbachmann** [comment]
It should work on most linux systems.
There's currently a problem on mac where the text gets outlined (converted to vectors).

**Comment by medikoo** [comment]
@marcbachmann Indeed I found that information also elsewhere. Wonder where should bug be reported for that (?)

**Comment by marcbachmann** [comment]
That should work now with the newest version. I've upgraded the module to phantomjs v2, which fixed the bug last month.
