### ISSUE TITLE
Prevent line split into two pages

### ISSUE THREAD

**Issue by desenvprimedb** [marcbachmann/node-html-pdf#633]
Is it possible to prevent a table line to be split into two pages?

![Screen Shot 2021-06-30 at 16 19 52](https://user-images.githubusercontent.com/77068693/124019483-7f245300-d9bf-11eb-953a-0ffa1ca7edcd.png)

**Comment by jeffersonveloso** [comment]
Any solution for this problem ?

**Comment by desenvprimedb** [comment]
No, I'm dropping this lib and creating a java based microservice with jasper reports.
