### ISSUE TITLE
CSS and SVGs not loading, when including the CSS via <style> Flex elements aren't displayed correctly.

### ISSUE THREAD

**Issue by BriniM** [marcbachmann/node-html-pdf#640]
I have tried all sort of variations, including a base property, file:// absolute paths and relative paths.

And finally when using <style> tags, elements with display: flex aren't displayed correctly.

Any helps / tips are appreciated, code: https://gist.github.com/BriniM/52cfbd2a026ff235f6e403f3eaa8790b

**Comment by Syno0** [comment]
Same here, nothing new ?

**Comment by Syno0** [comment]
Actually I found my problem, it was about @media screen (min-width) that where not trigger (because of the phantomJS virtual viewport that was too small I guess). Removing media screen from the CSS and so force the CSS to be considered fix my problem (It was with simple-grid.css plugins btw)

**Comment by BriniM** [comment]
> Same here, nothing new ?

I resorted to using a headless chrome version controlled by code, and that did the trick for generating PDFs for me.
