### ISSUE TITLE
image in image tag appearing as question mark.!

### ISSUE THREAD

**Issue by UjjualUSspericorn** [marcbachmann/node-html-pdf#650]
It was working fine till few weeks ago .Now the image appears like this. I have checked whether the url is valid. 

![image](https://user-images.githubusercontent.com/47880100/135265349-f84079f9-bc24-42b4-b466-7064aa10e08f.png)

@alexbor

**Comment by smaculan** [comment]
I have the same issue

**Comment by ye-yo** [comment]
I solved it in the following way.

var config = {
  ...
 localUrlAccess: true
}

<img src="file://{image folder path}/image.png}" >

**Comment by IsaevTimur** [comment]
Same problem, but from my Heroku instance. Locally on the dev server it's ok.

Does not solve the issue on my side.
` localUrlAccess: true`

I have remote images from CDN, instead of them I see "?" question marks. 

Probably relates more to phantomJS/Node version.
Any advice on where to dig it?

**Comment by Rohitpa7824** [comment]
I am facing the same issue. My html-pdf package is locked at 2.1.0

**Comment by Tudodesk** [comment]
I have the same issue does anyone have a resolve for this?

**Comment by ashishmadeti** [comment]
This might be linked to the recent [expiry of letsencrypt root certificate](https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/). In our experiments, we found out that using `request.get()` with node version v6.10.0 was throwing the error `certificate has expired` but it was working fine with node version v14.17.1.
I believe that older version of node might be using some old certificates.

For a quick fix, you can set `phantomArgs` to `--ignore-ssl-errors=yes` in the config object passed to `create()`.

**Comment by bweston92** [comment]
@ashishmadeti be prepared for a lot of thumbs up 👍

**Comment by TrumanRu** [comment]
> For a quick fix, you can set `phantomArgs` to `--ignore-ssl-errors=yes` in the config object passed to `create()`.

@ashishmadeti I really appreciate you for you tip. It helped me in my case.

But update to Node v14.18.0 didn't help me. Only `--ignore-ssl-errors=yes` saved my day.

**Comment by Tudodesk** [comment]
@TrumanRu where do we add this can you show some code?

**Comment by Tudodesk** [comment]
`"phantomArgs": [], // array of strings used as phantomjs args e.g. ["--ignore-ssl-errors=yes"]`

**Comment by TrumanRu** [comment]
> @TrumanRu where do we add this can you show some code?

``` JS
htmlPdf.create(html, {
            type: 'png',
            quality: 75,
            zoomFactor: 0.5,
            timeout: 120000,
            phantomArgs: ['--ignore-ssl-errors=yes'],
});
```

**Comment by Felwin** [comment]
> This might be linked to the recent [expiry of letsencrypt root certificate](https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/). In our experiments, we found out that using `request.get()` with node version v6.10.0 was throwing the error `certificate has expired` but it was working fine with node version v14.17.1. I believe that older version of node might be using some old certificates.
> 
> For a quick fix, you can set `phantomArgs` to `--ignore-ssl-errors=yes` in the config object passed to `create()`.

Saved our day

**Comment by UjjualUSspericorn** [comment]
It worked.!

**Comment by alexjs87** [comment]
It worked! +1
