### ISSUE TITLE
Footer: Footer has a default bottom margin 

### ISSUE THREAD

**Issue by khaledosama999** [marcbachmann/node-html-pdf#660]
for some reason the footer has some margin at the bottom that can't be removed I tried adding margin bottom with negative values but it didn't work
<img width="1404" alt="Screen Shot 2022-02-24 at 2 16 48 PM" src="https://user-images.githubusercontent.com/18629517/155522580-36782c2f-9cd9-4433-8e73-687918eb85b1.png">

I'm adding the footer using the `id=pageFooter` not the footer option

**Comment by iryna-martyniuk-techmagic** [comment]
@khaledosama999 I had top margin in footer, tried to remove it with css for the footer, didn't work. noticed that it was default browser's margin, using reset.css now, it removes some default browser styles and helped with that top margin. hope, it helps

**Comment by iryna-martyniuk-techmagic** [comment]
@khaledosama999 I had top margin in footer, tried to remove it with css for the footer, didn't work. noticed that it was default browser's margin, using reset.css now, it removes some default browser styles and helped with that top margin. hope, it helps
