### ISSUE TITLE
Font not showing

### ISSUE THREAD

**Issue by Avhishek05** [marcbachmann/node-html-pdf#663]
I am trying to create a table. In my local it is working fine. On production font not showing.
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/23546633/157882177-f04d7932-99f1-44cc-8291-53fc7c40db09.png">
I am not getting what is the issue here

**Comment by tmetade** [comment]
Can you provide more details on how you are running this?

**Comment by Avhishek05** [comment]
I was using this on secure server which doesn't allow external apis call. later I added font file also then fonts were showing
