### ISSUE TITLE
PDF in local environment is working perfectly, when I uploaded to production instead of one page it becomes 3 pages with spaces and different margins!

### ISSUE THREAD

**Issue by David-Pena** [marcbachmann/node-html-pdf#670]

**Comment by Wazbat** [comment]
Are the operating system's different? This seemed to solve it for us I think, setting the zoom

https://github.com/marcbachmann/node-html-pdf/issues/215

**Comment by David-Pena** [comment]
It's kind of similar, but in my case it wasn't two different operating system, instead it was zoomed in two different browsers but we fixed specifying the font size almost everywhere. Thank you for your answer.

**Comment by scush989898** [comment]
i got the same problem on production using heroku. The solution for me was creating a new env var OPENSSL_CONF with value /dev/null.

https://prnt.sc/VaOabzLAXFlO

i added to heroku env vars and it worked for me.
