### ISSUE TITLE
How do I handle authentication?

### ISSUE THREAD

**Issue by kevinfairclough** [marcbachmann/node-html-pdf#69]
The content of my page uses images that are also downloaded from my site, they fail with 401 errors. 

How do I pass the authenticated user onto the phantomjs process?

**Comment by marcbachmann** [comment]
We can easily add http header support. If we have that you can use basic authentication or set a custom header. Is that good enough for you?

**Comment by kevinfairclough** [comment]
Sounds good to me :-)
