### ISSUE TITLE
command line use?

### ISSUE THREAD

**Issue by dsoto** [marcbachmann/node-html-pdf#7]
Is it possible to use html-pdf from the command line?

**Comment by marcbachmann** [comment]
I don't want to have a submodule that needs additional dependencies.
If you like I can make a separate one. But I don't think it will be popular enough.

Here is a script that's probably enough for you (I haven't tested it, so sorry if it crashes :smile:)
If there's more demand I can move that code into a separate module.

You can call it like this:
`./create-pdf.js --src=/path/to/html-file.html --dst=/destination/path/to/the.pdf`

```javascript
#!/usr/bin/env node
var pdf = require('../');
var assert = require('assert');
var fs = require('fs');
var path = require('path');
var args = require('minimist')(process.argv.slice(2), {alias: {s: 'source', src: 'source', d: 'destination', dst: 'destination'}});

assert(args.source, 'A source is required');
assert(args.destination, 'A destination is required');

html = fs.readFileSync(path.resolve(args.source), 'utf8');
pdf.create(html).toFile(path.resolve(args.destination), function(err, res){
  if (err) {
   console.error(err.stack);
   process.exit(1);
  }
  else {
    console.log('File saved to ', res.filename);
  }
});
```

**Comment by marcbachmann** [comment]
Please let me know if you need more information.
