### ISSUE TITLE
'html-pdf: PDF generation timeout. Phantom.js script did not exit.' on Debian Wheezy

### ISSUE THREAD

**Issue by jrm2k6** [marcbachmann/node-html-pdf#8]
I have this issue on Debian Wheezy when running this code:

```
pdf.create(html, {
    width: '297mm',
    height: '400mm',
    directory: '/tmp/ramdisk',
    timeout: '60000'
    }, function(err, buffer) {});

```

After taking some time to check, and play around with html-pdf, here is what I did:
- I change the timeout to 10 minutes on my machine, still the same issue.
- I change the destination repository to be /tmp/ramdisk, as I had some issues before (in Python) with some IO work taking a really long time. I thought it might be related so I used some ramdisk instead, same issue.
- I tried to run the unit tests, only the first 5 are passing. It stucks on 'task watch..'
  I don't really know what to do now to make any progress.

**Comment by dv29** [comment]
I am facing same issue, my html is also correct, everything is ok but it does not work
`html-pdf` : 2.1.0

**Comment by leonjiresse** [comment]
Increase the timeout value option (Eg.):
`var options = {
        ...,
        timeout: 30000
    };`

**Comment by atrvicky** [comment]
I faced the issue recently on Ubuntu 22.04 LTS. Tried almost every solution here and nothing worked. Finally this helped me resolve it.

1. Install phantomjs on your local machine ([instructions](https://gist.github.com/julionc/7476620?permalink_comment_id=3877488))
2. In the `CreateOptions` that you pass to `pdf.create`, add `phantomPath`
Here is my updated `CreateOptions`

```javascript
 const pdfOptions = {
    format: "A4", // allowed units: A3, A4, A5, Legal, Letter, Tabloid
    orientation: "portrait", // portrait or landscape
    // Rendering options
    // base: assetPath, // Base path that's used to load files (images, css, js) when they aren't referenced using a host
    localUrlAccess: true, // Prevent local file:// access by passing '--local-url-access=false' to phantomjs
    type: "pdf", // allowed file types: png, jpeg, pdf,
    phantomPath: "/usr/local/bin/phantomjs", // the local installation of phantomjs (use which phantomjs after step 1 to get this path)
  };
```
