### ISSUE TITLE
No License information

### ISSUE THREAD

**Issue by Dsyko** [marcbachmann/node-html-pdf#82]
What license is this project under? MIT? Thanks!

**Comment by marcbachmann** [comment]
Yes, it's MIT. You can see that in the package.json file.
Should I mention that in the README or add a LICENSE file in order to make it clearer?

**Comment by bluesockets** [comment]
Yes please! I had to dig around and find this page in order to get clarity.

**Comment by Dsyko** [comment]
Yeah a LICENCE file would make it super obvious 👍

**Comment by squirrelsRduck** [comment]
or in the readme
