### ISSUE TITLE
npm install -g not creating symlink in /usr/local/bin

### ISSUE THREAD

**Issue by rbalicki2** [marcbachmann/node-html-pdf#91]
Hello,

I'm not sure if this is specific to my machine (probably is), but npm install -g html-pdf does not create a symlink in my /usr/local/bin folder to html-pdf, which (for example npm install -g gulp does).

I had to create the symlink with:

(cd /usr/local/bin/ && ln -s  /usr/local/Cellar/node/0.10.28/lib/node_modules/html-pdf/bin/index.js html-pdf)

NBD but maybe others have this issue as well.

Thank you for creating this package!

-R

**Comment by marcbachmann** [comment]
This depends on the installation procedure. Most likely people are using the official installer, which creates a symlink to that directory upon `npm install -g` (afaik). I myself use `nvm`, which has its own bin directory: e.g. `$HOME/.nvm/versions/node/v4.2.2/bin/`
In your case the executables are probably in `/usr/local/Cellar/node/0.10.28/lib/node_modules/.bin` or `/usr/local/Cellar/node/0.10.28/bin`.  So you might have to add that directory to your `PATH` variable.

**Comment by rbalicki2** [comment]
Ah, you're right, this is specific to my machine. I'm looking into it now. Thank you.
