### ISSUE TITLE
Text is not selectable and text only pdf is 11mb

### ISSUE THREAD

**Issue by kilianc** [marcbachmann/node-html-pdf#95]
I guess this module creates a raster of every page instead of a proper pdf?

**Comment by cozzbie** [comment]
Interested in getting a sample file and looking at it. Please upload and share link.

**Comment by kilianc** [comment]
@cozzbie I will be able to upload in 2 days. I am traveling at the moment. BTW I have seen this happening on mac osx, I have fixed this issue running the script in a docker container and using an alternative phantomjs

    FROM kilianciuffolo/node:5.2.0

    # pkgs
    RUN \
      apt-get update && \
      apt-get install --no-install-recommends -y -q \
        bzip2 \
        libwebp5 \
        libfontconfig \
        libjpeg62 \
        libssl1.0.0 \
        libicu52 \
        && \
      apt-get clean autoclean && \
      apt-get autoremove -y && \
      rm -rf /var/lib/{apt,dpkg,cache,log}/

    RUN \
      curl -s \
        -L https://astefanutti.github.io/decktape/downloads/phantomjs-linux-debian8-x86-64 \
        -o /bin/phantomjs && \
      chmod +x bin/phantomjs

    WORKDIR /app
    COPY package.json ./
    RUN npm i && npm cache clean

    COPY fonts/* /usr/share/fonts/

    COPY . .
    RUN ./node_modules/.bin/gulp

The above will output a 100k pdf with selectable text.

**Comment by tamlyn** [comment]
I have the same problem. Simple HTML file `<h1>Testing</h1>` comes out as single image when run on OS X but works when run on Ubuntu.

[test-darwin.pdf](https://github.com/marcbachmann/node-html-pdf/files/99504/test-darwin.pdf)
[test-ubuntu.pdf](https://github.com/marcbachmann/node-html-pdf/files/99505/test-ubuntu.pdf)

Versions:
- html-pdf 1.4.0
- PhantomJS 1.9.19
- Ubuntu 14.04
- OS X 10.10.5

**Comment by purepear** [comment]
Same problem here

according to this issue in markdown-pdf https://github.com/alanshaw/markdown-pdf/issues/37 the last version of phantomjs fixed the issue

i guess it's time to bump up phantomjs #106

**Comment by marcbachmann** [comment]
Fixed in v2.0.0 by upgrading to phantomjs v2

**Comment by taylorwan** [comment]
I'm seeing this issue on Ubuntu Trusty 14.04, but runs perfectly on OS X 10.11.6. Would you be able to look into this @marcbachmann?

Versions
html-pdf: 2.1.0
phantomjs-prebuilt: 2.1.13

Examples
[Generated by OS X 10.11.6](http://fn-downloads-proxy-staging-lb-360162730.us-east-1.elb.amazonaws.com/no_bills_201704041439_1uwmvnj04udupvxcvo9d5f80k9.pdf?Expires=1522867197&Signature=4WxOBcNa54hPsMLj9RF4nLgxgnM%3D)
[Generated by Ubuntu Trusty 14.04](http://fn-downloads-proxy-prod-lb-1401633066.us-east-1.elb.amazonaws.com/no_bills_201704041835_597t1cw5xt4eqjodh78fjvpldi.pdf?Expires=1522866936&Signature=LN6oGR3e3msSbeQONaEiSLmvqmY%3D)

**Comment by earllee** [comment]
Hi @marcbachmann,

I'm also running into the same issue. When html-pdf runs on Ubuntu, the PDF contains only images and no selectable text. Any idea why this may occur? Thanks!

**Comment by marcbachmann** [comment]
Install libfontconfig. That should help.

**Comment by earllee** [comment]
@marcbachmann thanks for the suggestion! Appreciate the speedy response. Seems like I have libfontconfig installed on my Linux server. Have you heard of any other potential solutions?

**Comment by DigitalLeaves** [comment]
Any news about this issue? Experiencing the same problem.

**Comment by DigitalLeaves** [comment]
I managed to identify the problem and solve it. 

For anyone in the same situation: The problem happens probably because you are using custom fonts in your document, and loading them remotely (i.e: Google fonts). Loading the truetype or web font from the remote URL causes PhantomJS to rasterize the font in the PDF instead of adding text as just text.

So the solution is to include the fonts locally. Create a fonts directory where your templates or .html files are, and then include the local fonts. The size reduction will be effective and the PDF will be a "text PDF" also, instead of a rasterized image PDF.

So change this:
```
<head>
    <meta charset="utf-8">
    <title>Your title</title>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    ...
</head>
```

For this: 
```
<head>
    <meta charset="utf-8">
    <title>Your title</title>
    <style>
    @font-face {
        font-family: 'Lato';
        font-style: normal;
        font-weight: 400;
        src: local('Lato'), local('Lato-Regular'), url(./fonts/Lato-Regular.ttf) format('truetype');
    }
    @font-face {
        font-family: 'Lato';
        font-style: normal;
        font-weight: 700;
        src: local('Lato'), local('Lato-Bold'), url(./fonts/Lato-Bold.ttf) format('truetype');
    }
    </style>
```

And it will work on your remote server as well.

**Comment by eladnava** [comment]
Cheers @DigitalLeaves for the excellent workaround 👍

**Comment by eladnava** [comment]
Worth mentioning that `woff2` fonts aren't supported. Use `ttf` instead.

**Comment by eladnava** [comment]
In the end, I had to actually install the fonts locally in `/usr/share/fonts` of Amazon Linux to finally get the PDF text to be selectable. Including the `ttf` font files locally and linking to them made the text show up in the right font, but it wasn't selectable/editable in the PDF. Only when installed as a system font followed by `sudo fc-cache` was the text selectable.

**Comment by jinoantony** [comment]
@DigitalLeaves Thanks, that worked!
