### ISSUE TITLE
Inline HTML tag support

### ISSUE THREAD

**Issue by jpike88** [marcbachmann/node-html-pdf#96]
This allows a header or footer to be switched on/off depending on the page that tag ends up on.

<htmlpageheader>

</htmlpageheader>

This allows there to be no header page 1 or 2, but show on page 3 only etc

**Comment by marcbachmann** [comment]
That's somewhat supported in v1.5: https://github.com/marcbachmann/node-html-pdf/releases/tag/1.5.0
There's also an example: https://github.com/marcbachmann/node-html-pdf/blob/master/test/multiple-pages.html
