### ISSUE TITLE
Watermark support

### ISSUE THREAD

**Issue by jpike88** [marcbachmann/node-html-pdf#97]
Some PDFs are used for preview and should have the ability to have a watermark image stamped on all pages to discourage piracy.

**Comment by manuel-interaction** [comment]
@jpike88 Any answer on this at all? Or were you able to come up with any workaround on your own? I feel like this is an important feature that should be taken into account.

**Comment by marcbachmann** [comment]
Maybe you can try something with  the `@page` selector.
```
@page {
  background: url('./some-image')
}
```

Maybe it also has an `::after` pseudo element.

**Comment by jpike88** [comment]
I gave up and used mPDF, it's in PHP but piping to it and back was worth it

**Comment by ezzygemini** [comment]
+1

**Comment by natarajanmca11** [comment]
Is there any example html page is available for watermark.
